# the footer of your site
cdn:
  # These base libraries cannot be deleted
  jquery: https://jsd.onmicrosoft.cn/npm/jquery@3.5/dist/jquery.min.js
  vue: https://jsd.onmicrosoft.cn/npm/vue@2.6/dist/vue.min.js
  # When these CDN resources are deleted, local resources are loaded.
  common: https://jsd.onmicrosoft.cn/gh/xaoxuu/hexo-theme-resume@1.0.0/source/js/common.js
  escape: https://jsd.onmicrosoft.cn/gh/xaoxuu/hexo-theme-resume@1.0.0/source/js/css.escape.js
  smooth_scroll: https://jsd.onmicrosoft.cn/gh/xaoxuu/hexo-theme-resume@1.0.0/source/js/smooth-scroll.min.js
  # css: https://cdn.jsdelivr.net/gh/xaoxuu/hexo-theme-resume@1.0.0/source/css/style.min.css
  # Optional plug-in: image zoom
  fancybox:
    css: https://jsd.onmicrosoft.cn/npm/@fancyapps/fancybox@3.5/dist/jquery.fancybox.min.css
    js: https://jsd.onmicrosoft.cn/gh/fancyapps/fancybox@3.5/dist/jquery.fancybox.min.js
    
copyright: '[版权所有 © 2023 河山, 此网站使用 Hexo 搭建](/)'
